Models/Domains/Invoice.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace InvoiceManager.Models.Domains
{
    public class Invoice
    {

        public Invoice()
        {
            InvoicePositions = new Collection<InvoicePossition>();
        }
        public int Id { get; set; }
        [Required(ErrorMessage ="Pole Tytuł jest wymagane !!!")]
        [Display(Name = "Tytuł faktury")]
        public string Title { get; set; }
        [Display(Name = "Wartość")]
        public decimal Value { get; set; }
        [Display(Name = "Sposób płatności")]
        public int MethodOfPaymentId { get; set; }
        [Display(Name = "Termin Płatności")]
        public DateTime PaymentDate { get; set; }
        [Display(Name = "Data Wystawienia")]
        public DateTime CreatedDate { get; set; }
        [Display(Name = "Uwagi")]
        public string Comments { get; set; }
        [Display(Name = "Klient")]
        public int ClientId { get; set; }
        [Required]
        [ForeignKey("User")]
        public string UserId { get; set; }
        [Display(Name = "Sposób płatności")]
        public MethodOfPayment MethodOfPayment { get; set; }
        public Client Client { get; set; }
        public ApplicationUser User { get; set; }
        public ICollection<InvoicePossition> InvoicePositions { get; set; }
    }
}

Controllers/HomeController.cs
using InvoiceManager.Models.Domains;
using InvoiceManager.Models.Repositories;
using InvoiceManager.Models.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

namespace InvoiceManager.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {

        private InvoiceRepository _invoiceRepository = new InvoiceRepository();
        private ClientRepository _clientRepository = new ClientRepository();
        private ProductRepository _productRepository = new ProductRepository();

        [NonAction]
        public int Testy()
        {
            return 1;
        }

        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var invoices = _invoiceRepository.GetInvoices(userId);
            return View(invoices);
        }

        #region Invoice 
        
        public ActionResult Invoice(int id = 0)
        {
            var userId = User.Identity.GetUserId();
            var invoice = id == 0 ?
                GetNewInvoice(userId) :
                _invoiceRepository.GetInvoice(id, userId);

            var vm = PrepareInvoiceVm(invoice, userId); 

            return View(vm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Invoice(Invoice invoice)
        {
            var userId = User.Identity.GetUserId();
            invoice.UserId = userId;

            //System.IO.File.AppendAllText(@"d:\plik.txt",$"{invoice.Title} {invoice.PaymentDate} \n");

            if (!ModelState.IsValid)
            {
                var vm = PrepareInvoiceVm(invoice, userId);
                return View("Invoice", vm);
            } 

            if (invoice.Id == 0)
                _invoiceRepository.Add(invoice);
            else
                _invoiceRepository.Update(invoice);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult DeleteInvoice(int invoiceId)
        {
            try
            {
                var userId = User.Identity.GetUserId();
                _invoiceRepository.Delete(invoiceId, userId);
            }
            catch (Exception exception)
            {
                // TODO: logowanie do pliku niepowodzenie usunięcia faktury
                return Json(new { Success = false, Message = exception.Message });
            }

            return Json(new { Success = true });
        }

        private EditInvoiceViewModel PrepareInvoiceVm(Invoice invoice, string userId)
        {
            return new EditInvoiceViewModel
            {
                Invoice = invoice,
                Heading = invoice.Id == 0 ? "Dodawanie Nowej Faktury" : "Edycja",
                Clients = _clientRepository.GetClients(userId),
                MethodOfPayments = _invoiceRepository.GetMethodOfPayment()
            };
        }

        private Invoice GetNewInvoice(string userId)
        {
            return new Invoice
            {
                UserId = userId,
                CreatedDate = DateTime.Now,
                PaymentDate = DateTime.Now.AddDays(7)
            };
        }

        #endregion

        #region InvoicePossition

        [HttpGet]
        public ActionResult InvoicePosition(int invoiceId = 0, int invoicePositionId = 0)
        {
            var userId = User.Identity.GetUserId();
            var invoicePosition = invoicePositionId == 0 ?
                GetNewInvoicePosition(invoiceId, invoicePositionId) :
                _invoiceRepository.GetInvoicePosition(invoicePositionId,userId);


            var vm = PrepareInvoicePositionVm(invoicePosition);
            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult InvoicePosition(InvoicePossition invoicePosition)
        {
            var userId = User.Identity.GetUserId();
            // zweryfikujemy, czy uzytkownik próbuje zaktualizować swoją fakturę
            // dodajemy lub aktualizujemy pozycję faktury
            // wyliczymy wartość pozycji
            // wyliczymy i zaktualizujemy wrtość faktury


            if (!ModelState.IsValid)
            {
                var vm = PrepareInvoicePositionVm(invoicePosition);
                return View("InvoicePosition", vm);
            }

            var product = _productRepository.GetProduct(invoicePosition.ProductId);
            invoicePosition.Value = product.Value * invoicePosition.Quantity;

            if (invoicePosition.Id == 0)
                _invoiceRepository.AddPosition(invoicePosition, userId);
            else
                _invoiceRepository.UpdatePosition(invoicePosition, userId);

            _invoiceRepository.UpdateInvoiceValue(invoicePosition.InvoiceId, userId);

            return RedirectToAction("Invoice", new { id = invoicePosition.InvoiceId });
            
        }

        [HttpPost]
        public ActionResult DeleteInvoicePosition(int positionId, int invoiceId)
        {
            var invoiceValue = 0m;

            try
            {
                var userId = User.Identity.GetUserId();
                _invoiceRepository.DeletePosition(positionId,invoiceId, userId);
                // musimy jeszcze zaktualizować wartość faktury
                invoiceValue = _invoiceRepository.UpdateInvoiceValue(invoiceId, userId);
            }
            catch (Exception exception)
            {
                // TODO: logowanie do pliku niepowodzenie usunięcia faktury
                return Json(new { Success = false, Message = exception.Message });
            }

            return Json(new { Success = true, InvoiceValue = invoiceValue });
        }

        private EditInvoicePositionViewModel PrepareInvoicePositionVm(InvoicePossition invoicePosition)
        {
            return new EditInvoicePositionViewModel
            {
                InvoicePosition = invoicePosition,
                Heading = invoicePosition.Id == 0 ?
                "Dodawanie nowej pozycji" :
                "Edycja Pozycja",
                Products = _productRepository.GetProducts()
            };
        }

        private InvoicePossition GetNewInvoicePosition(int invoiceId, int invoicePositionId)
        {
            return new InvoicePossition
            {
                InvoiceId = invoiceId,
                Id = invoicePositionId
            };
        }

        #endregion

        public static int number = 0; 
        [AllowAnonymous]
        [OutputCache(Duration = 10)]
        public ActionResult Contact()
        {
            number++;
            ViewBag.Message = "Your contact page." + number;

            return View();
        }


        [AllowAnonymous]
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            var valSession = GetSession();
            valSession++;
            UpdateSession(valSession);
            ViewBag.ValSession = valSession;

            var valCookie = GetCookie();
            valCookie++;
            UpdateCookie(valCookie);
            ViewBag.ValCookie = valCookie;

            var valCache = GetCache();
            valCache++;
            UpdateCache(valCache);
            ViewBag.ValCache = valCache;


            return View();
        }

        private void UpdateSession(int i)
        {
            Session["klucz"] = i;
        }

        private int GetSession()
        {
            if (Session["klucz"] != null)
                return (int)Session["klucz"];
            return 0;
        }

        private void UpdateCookie(int i)
        {
            var cookie = new HttpCookie("klucz",i.ToString());
            cookie.Expires = DateTime.Now.AddDays(365);
            Response.SetCookie(cookie);
        }

        private int GetCookie()
        {
            if (Request.Cookies["klucz"] != null)
                return int.Parse(Request.Cookies["klucz"].Value);
            return 0;
        }


        private void UpdateCache(int i)
        {
               HttpRuntime.Cache["klucz"] = i;
        }

        private int GetCache()
        {
            if (HttpRuntime.Cache["klucz"] != null)
                return (int)HttpRuntime.Cache["klucz"];
            return 0;
        }


    }
}

Controllers/PrintController.cs
using InvoiceManager.Models.Domains;
using InvoiceManager.Models.Repositories;
using Microsoft.AspNet.Identity;
using Rotativa;
using Rotativa.Options;
using System;
using System.Web.Mvc;


namespace InvoiceManager.Controllers
{
    [Authorize]
    public class PrintController : Controller
    {
        private InvoiceRepository _invoiceRepository = new InvoiceRepository();
        public ActionResult InvoiceTemplate(int id)
        {
            var userId = User.Identity.GetUserId();
            var invoice = _invoiceRepository.GetInvoice(id,userId);

            return View(invoice);
        }
        
        [HttpPost]
        public ActionResult InvoiceToPdf(int id)
        {
            var handle = Guid.NewGuid().ToString();
            var userId = User.Identity.GetUserId();
            var invoice = _invoiceRepository.GetInvoice(id, userId);
            
            TempData[handle] = GetPdfContent(invoice);

          
            return Json(new
            {
                Success = true,
                FileGuid = handle,
                FileName = $@"Faktura_{invoice.Id}.pdf"
            });
        }

        private byte[] GetPdfContent(Invoice invoice)
        {
            var pdfResult = new ViewAsPdf(@"InvoiceTemplate", invoice)
            {
                PageSize = Size.A4,
                PageOrientation = Orientation.Portrait
            };

            return pdfResult.BuildFile(ControllerContext);
        }

        public ActionResult DownloadInvoicePdf(string fileGuid, string fileName)
        {

            if (TempData[fileGuid] == null)
                throw new Exception("Błąd przy próbie eksportu faktury do PDF.");

            var data = TempData[fileGuid] as byte[];

            return File(data, "application/pdf", fileName);
        }

    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>
<h3>sesja: @ViewBag.ValSession</h3>
<h3>cookie: @ViewBag.Valcookie</h3>
<h3>cache: @ViewBag.ValCache</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@model IEnumerable<InvoiceManager.Models.Domains.Invoice>

@{
    ViewBag.Title = "Faktury";
}

<h1 class="mb-3">Faktury</h1>

<button 
        class="btn btn-primary mb-3"
        onclick='window.location.href = "@Url.Action("Invoice","Home")"'>
    Dodaj
</button>

@if (Model != null && Model.Any())
{
<table class="table table-hover table-striped mt-3 mt-5">
    <thead>
        <tr>
            <th scope="col">tytuł</th>
            <th scope="col">klient</th>
            <th scope="col">wartość</th>
            <th scope="col">data</th>
            <th scope="col">termin</th>
            <th scope="col"> </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var invoice in Model)
        {
        <tr>
            <td>
                <a 
                   class="font-weight-bold"
                   href="@Url.Action("Invoice","Home", new { id = invoice.Id })">
                   @invoice.Title
                </a>
            </td>
            <td>@invoice.Client.Name</td>
            <td>@invoice.Value zł</td>
            <td>@invoice.CreatedDate.ToString("dd-MM-yyyy")</td>
            <td>@invoice.PaymentDate.ToString("dd-MM-yyyy")</td>
            <td>
                <button 
                        class="btn btn-danger btn-sm"
                        onclick="deleteInvoice('@invoice.Id',this)">
                Usuń Fakturę
                </button>
            </td>
        </tr>
        }

    </tbody>
</table>

}
else
{
    <div>
        Brak faktur do wyświetlenia
    </div>
}     


@section scripts
{
    <script type="text/javascript">
        // --------------------------------------------
        function deleteInvoice(id, btn) {
            if (!confirm("Czy na pewno chcesz usunąć fakturę ?"))
                return;

            $.ajax({
                type: 'POST',
                url: "@Url.Action("DeleteInvoice","Home")",
                data: {
                    invoiceId: id
                },
                success: function (data) {
                    if (data.Success) {
                        // usuwanie z tabeli w html'u
                        var row = btn.parentNode.parentNode;
                        row.parentNode.removeChild(row);
                    }
                    else {
                        alert(data.Message);
                    }
                },
                error: function (data) {
                        alert(data.Message);
                },
                dataType: 'json'
                
                });
            // --------------------------------------------
        }
    </script>
}

Views/Home/Invoice.cshtml
@model InvoiceManager.Models.ViewModels.EditInvoiceViewModel

@{
    ViewBag.Title = Model.Heading;
}

<h2>@Model.Heading</h2>

<div>
    @Model.Invoice.PaymentDate
</div>

@if (Model.Invoice.Id != 0)
{
    <button class="btn btn-primary mb-3"
            onclick='window.location.href = "@Url.Action("InvoicePosition","Home",new { invoiceId = Model.Invoice.Id })"'>
        Dodaj pozycję
    </button>

    <button class="btn btn-secondary mb-3"
            onclick="generatePdf()">
        Generuj PDF
    </button>

    <button id="printButton" class="btn btn-secondary mb-3">
        Drukuj 1
    </button>

    <button class="btn btn-secondary mb-3" onclick="printInvoice()">
        Drukuj 2
    </button>
}


<div class="row">
    <div class="col-lg-6">
        @using (Html.BeginForm("Invoice", "Home"))
        {
            @Html.AntiForgeryToken()

            <!-- Wyświetlenie podsumowania walidacji-->
            @Html.ValidationSummary()

            if (Model.Invoice.Id == 0)
            {
                <p class="alert alert-info mb-4 mt-4">Pola tytuł, klient, sposób płatności i termin są <strong>wymagane</strong> </p>
            }

            @Html.HiddenFor(x => x.Invoice.Id)
            @Html.HiddenFor(x => x.Invoice.UserId)

            <div class="form-group mb-3">
                @Html.LabelFor(x => x.Invoice.Title)
                @Html.TextBoxFor(x => x.Invoice.Title,
               new { @class = "form-control", autofocus = "autofocus" })
                @Html.ValidationMessageFor(x => x.Invoice.Title)
            </div>

            <div class="form-group mb-3">
                @Html.LabelFor(x => x.Invoice.ClientId)
                @Html.DropDownListFor(x => x.Invoice.ClientId,
               new SelectList(Model.Clients, "Id", "Name"),
               "--- Wybierz klienta ---",
               new { @class = "form-control", autofocus = "autofocus" })
                @Html.ValidationMessageFor(x => x.Invoice.ClientId)
            </div>

            if (Model.Invoice.Id != 0)
            {
                <div class="form-group mb-3">
                    @Html.LabelFor(x => x.Invoice.Value)
                    @Html.TextBoxFor(x => x.Invoice.Value,
                   new { @class = "form-control", @readonly = "readonly" })
                </div>
            }

            <div class="form-group mb-3">
                @Html.LabelFor(x => x.Invoice.MethodOfPaymentId)
                @Html.DropDownListFor(x => x.Invoice.MethodOfPaymentId,
               new SelectList(Model.MethodOfPayments, "Id", "Name"),
               "--- Wybierz rodzaj płatności ---",
               new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Invoice.MethodOfPaymentId)
            </div>

            <div class="form-group mb-3">
                @Html.LabelFor(x => x.Invoice.PaymentDate)
                @Html.TextBoxFor(x => x.Invoice.PaymentDate,
                 "{0:dd-MM-yyyy}",
                new
                {
                    @class = "form-control",
                    @id = "PaymentDate",
                    autocomplete = "off"
                })
                @Html.ValidationMessageFor(x => x.Invoice.PaymentDate)
            </div>


            <div class="form-group mb-3">
                @Html.LabelFor(x => x.Invoice.Comments)
                @Html.TextAreaFor(x => x.Invoice.Comments,
               new { @class = "form-control" })
            </div>

            <button class="btn btn-primary btn-lg mb-5" type="submit">
                Zapisz
            </button>



        }
    </div>

    <div class="col-5 offset-1">
        @if (Model.Invoice.Id != 0)
        {
            @Html.Partial("_InvoicePositions", Model.Invoice.InvoicePositions)
        }
    </div>
</div>

@section scripts
{
    <script type="text/javascript">

           $("#printButton").click(function () {
             window.open("@Url.Action("InvoiceTemplate", "Print",new {id = Model.Invoice.Id })", "_blank",
            "menubar=no, toolbar=no, resizable=no, top=100, left=200, width=1000, height=800");
            });

        // ------

        function printInvoice() {
            var url = '@Url.Action("InvoiceTemplate", "Print")' + '?id=' + '@Model.Invoice.Id';

            var url = '@Url.Action("InvoiceTemplate", "Print", new { id = Model.Invoice.Id })';

            var myWindow = window.open(url, '', 'width=800,height=600');

            myWindow.onload = function () {
                myWindow.print();
                myWindow.onafterprint = function () {
                    myWindow.close();
                };
            };
        }


        // Generowanie PDF'a
        function generatePdf() {

            if (!confirm("Czy generujemy PDF ?"))
                return;
            // --------------------------------------------
            $.ajax({
                type: 'POST',
                url: "@Url.Action("InvoiceToPdf", "Print")",
                 data: {
                     id: '@Model.Invoice.Id'
                },
                success: function (data) {
                    if (data.Success) {

                        window.location = '@Url.Action("DownloadInvoicePdf", "Print")'
                            + '?fileGuid=' + data.FileGuid + '&fileName=' + data.FileName;

                    }
                    else {
                        alert(data.Message + ' x');
                    }
                },
                error: function (data) {
                        alert(data.Message);
                },
                dataType: 'json',
                cache: false

                });
            // --------------------------------------------
        }

        // Usuwanie pozycji faktury
        // funkcja wywoływana z widoku częściowego _InvoicePositions
        // Ważne aby była właśnie tytaj, czyli w widoku z którego jest
        // wywoływany widok częściowy
        function deleteInvoicePosition(positionId, invoiceId, btn) {
            if (!confirm("Czy na pewno chcesz usunąć pozycję faktury ?"))
                return;

             $.ajax({
                type: 'POST',
                url: "@Url.Action("DeleteInvoicePosition", "Home")",
                 data: {
                     positionId: positionId,
                     invoiceId: invoiceId
                },
                success: function (data) {
                    if (data.Success) {
                        // usuwanie z tabeli w html'u
                        var row = btn.parentNode.parentNode;
                        row.parentNode.removeChild(row);

                        var invoiceVal = data.InvoiceValue;
                        $('#Invoice_Value').val(data.InvoiceValue.toFixed(2).replace(".", ","));
                    }
                    else {
                        alert(data.Message);
                    }
                },
                error: function (data) {
                        alert(data.Message);
                },
                dataType: 'json'

                });
            // --------------------------------------------
        }

        $(document).ready(function () {

            // w formatowaniu ma być precinek, a nie kropka
            $.validator.methods.number = function (value, element) {
                return this.optional(element) || /^-?(?:\d+|\{1,3}(?:[\s\.,]\d{3})+)(?:[\.,]\d+)?$/.test(value);
            }

            // format daty
            $.validator.methods.date = function (value, element) {
                var isChrome = /Chrome/.test(navigator.userAgent) && /Google Inc/.test(navigator.vendor);
                var isFirefox = /Firefox/.test(navigator.userAgent);
                if (isChrome || isFirefox) {
                    var d = new Date();
                    return this.optional(element) || !/Invalid|NaN/.test(new Date(d.toLocaleDateString(value)));
                } else {
                    return this.optional(element) || !/Invalid|NaN/.test(new Date(value));
                }
            }


            $('#PaymentDate').datepicker({
                format: "dd-mm-yyyy",
                language: "pl",
                multidate: false,
                autoclose: true,
                todayHighlight: true,
                forceParse: false
            });
        });

    </script>
}

Views/Home/InvoicePosition.cshtml
@model InvoiceManager.Models.ViewModels.EditInvoicePositionViewModel


@{
    ViewBag.Title = Model.Heading;
}

<h2>@Model.Heading</h2>

@using (Html.BeginForm("InvoicePosition", "Home"))
{
    @Html.AntiForgeryToken()
     
    if (Model.InvoicePosition.Id == 0)
    {
        <p class="alert alert-info mb-4 mt-4">
            Pola: Lp, Produkt, Ilość i Wartość są
            <strong>wymagane</strong>
        </p>
    }
    @Html.HiddenFor(x => x.InvoicePosition.Id)
    @Html.HiddenFor(x => x.InvoicePosition.InvoiceId)

    <div class="form-group mb-3">
        @Html.LabelFor(x => x.InvoicePosition.Lp)
        @Html.TextBoxFor(x => x.InvoicePosition.Lp,
       new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.InvoicePosition.Lp)
    </div>

    <div class="form-group mb-3">
        @Html.LabelFor(x => x.InvoicePosition.ProductId)
        @Html.DropDownListFor(x => x.InvoicePosition.ProductId,
       new SelectList(Model.Products, "Id", "Name"),
       "--- Wybierz produkt ---",
       new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.InvoicePosition.ProductId)
    </div>

    <div class="form-group mb-3">
        @Html.LabelFor(x => x.InvoicePosition.Quantity)
        @Html.TextBoxFor(x => x.InvoicePosition.Quantity,
       new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.InvoicePosition.Quantity)
    </div>


    if (true)
    {
        <div class="form-group mb-3">
            @Html.LabelFor(x => x.InvoicePosition.Value)
            @Html.TextBoxFor(x => x.InvoicePosition.Value,
           new { @class = "form-control", @readonly = "readonly" })
        </div>
    }

    <button class="btn btn-primary btn-lg" type="submit">
        Zapisz
    </button>

}



@section scripts
{
    <script type="text/javascript">
        // --------------------------------------------

        $(document).ready(function () {

            // w formatowaniu ma być precinek, a nie kropka
            $.validator.methods.number = function (value, element) {
                return this.optional(element) || /^-?(?:\d+|\{1,3}(?:[\s\.,]\d{3})+)(?:[\.,]\d+)?$/.test(value);
            }
        });

    </script>
}

Views/Home/_InvoicePositions.cshtml
@model IEnumerable<InvoiceManager.Models.Domains.InvoicePossition>

<div class="row">
    <h2>Pozycje Faktury</h2>

        <table class="table table-hover table-striped mt-3 mb-5">
        <thead>
            <tr>
                <th scope="col">lp</th>
                <th scope="col">Produkt</th>
                <th scope="col">Ilość</th>
                <th scope="col">Wartość</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>





            @if (true)
            {


                foreach (var position in Model)
                {
                    <tr>

                        <td>
                            <a class="font-weight-bold"
                               href="@Url.Action("InvoicePosition", "Home",
                                                            new { invoiceId = position.InvoiceId, 
                                                                invoicePositionId = position.Id } )"
                            >
                                @position.Lp
                            </a>
                        </td>
                        <td>@position.Product.Name</td>
                        <td>@position.Quantity</td>
                        <td>@position.Value zł</td>
                        <td>
                            <button class="btn btn-danger btn-sm"
                                    onclick="deleteInvoicePosition('@position.Id','@position.InvoiceId',this)">
                                Usuń Pozycję
                            </button>
                        </td>
                    </tr>
                }
            }

        </tbody>
    </table>
</div>